# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request Prerequisite Checks

on:
  push:
    branches:
      - 'GHA-pipeline-e2e'

  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.25.0-focal

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          # fatal: detected dubious ownership in repository at '/__w/golden-sample-app/golden-sample-app'
          chown -R $(id -u):$(id -g) $PWD

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'main'

      - name: Setup Node with version 16
        uses: ./.github/actions/setup-node
        with:
          npmUsername: ${{ secrets.MAVEN_USERNAME }}
          npmPassword: ${{ secrets.MAVEN_PASSWORD }}      
        
      - name: Build app
        run: npm run affected:build

      - name: Check Formatting
        run: npm run format:check  

      - name: Unit test
        run: npm run affected:test

      - name: Check Linting
        run: npm run affected:lint

      - name: Run e2e tests
        run: npm run e2e

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
