version: "3"
services:
  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "9999:9999"
    volumes:
      - ./mappings:/home/wiremock/mappings
      - ./__files:/home/wiremock/__files
    entrypoint: ["/docker-entrypoint.sh", "--verbose", "--port=9999"]
